apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-knative
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: dev.local/hello-knative:local
          env:
            - name: TARGET
              value: "Knative !!"
          imagePullPolicy: Never