apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-private-function
  namespace: default
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: dev.local/hello-private-function:local
          env:
            - name: TARGET
              value: " Private function !! "
          imagePullPolicy: Never